# Conexão com o Banco
spring.datasource.url=postgresql://postgres:JCzhmYJdbuUgQxpCOVpEbUxXoHpGfQcB@viaduct.proxy.rlwy.net:28890/railway
spring.datasource.username=${postgres}
spring.datasource.password=${JCzhmYJdbuUgQxpCOVpEbUxXoHpGfQcB}